### ISSUE TITLE
ChangeWindows Athaia project overview

### ISSUE THREAD

**Issue by Studio384** [ChangeWindows/Athaia#1]
ChangeWindows "Athaia" 8 is the next major version - and yet another rewrite - of ChangeWindows.

## Why

We've been trying to make some major changes to the v7 code base for nearly a year now. We've started and restarted various attempt at a v7.9 and v8.0 and I never was happy with either. A large part of this issue is the convoluted folder structure for our frontend, the fact that it is based on Bootstrap, and the absolute mess of components and CSS that v7 has become.

So, Athaia is being built from the ground up. Not only will the frontend and backend be their own separate projects (within this mono repo, to be clear), but we'll also build the front-end with more modern tools like Joy UI and take a serious look at revamping some of our existing features, including - but not limited to - finally tackeling ChangeWindows/ChangeWindows#171.

When all is said and done, this repository will take ChangeWindows/ChangeWindows's place, and our old v7 codebase will be moved to ChangeWindows/ChangeWindows7.

## How

Our goal isn't to directly replace all of ChangeWindows. We'll do this in 2 steps; the Windows Feature Store Explorer first, followed by the classic ChangeWindows.

### Phase 0 - Setup
When this phase is done, we're basically just ready to get started. Nothing from this will go up.

```[tasklist]
### Setup
- [ ] https://github.com/ChangeWindows/Athaia/issues/2
- [ ] https://github.com/ChangeWindows/Athaia/issues/3
- [ ] Preliminary User Interface
- [ ] Setup accounts, profile & settings
```

### Phase 1 - Windows Feature Store Explorer

For the first phase, we'll focus on building out the Windows Feature Store Explorer (WFSE). This is a major concern and given the extensiveness of the amount of data that is to be imported with this, this is something I want out of the way as fast as possible. As this can be hosted when it's done as an early preview of Athaia, it will also be the biggest value add we can give to ChangeWindows as it is today.
 
Addresses ChangeWindows/ChangeWindows#171

```[tasklist]
### Windows Feature Store Explorer
- [ ] Create Database migrations for Windows Feature Store Explorer
- [ ] View all Windows Feature Store ids throughout all builds
- [ ] View all Windows Feature Store ids from a single build
- [ ] Compare function to compare any build's feature ids with another
- [ ] Import data from Mach2
- [ ] Support user-generated content, allow users to publish human readable flag names and descriptions
- [ ] Setup TipTap editor
- [ ] Release ChangeWindows 7.9 with the removal of "Flags", link to Athaia
- [ ] Start hosting backend on `api.changewindows.org`
- [ ] Start hosting frontend on `athaia.changewindows.org`
```

### Phase 2 - ChangeWindows

This phase will focus on rebuilding the classic ChangeWindows. As this phase nears feature-completion we should start hosting it on `preview.changewindows.org`. Before we do that, we should assure that the API is stable and ready to move to v1 (as a beta).

```[tasklist]
### Windows Feature Store Explorer
- [ ] Add platform management
- [ ] Add release system with channels
- [ ] Implement timeline, unified platform pages
- [ ] Import data from Horizon
- [ ] Start hosting frontend on `preview.changewindows.org`
```

### Phase 3 - The Extras

Phase 3 will focus on building whatever comes to mind that makes sense. These changes should not create breaking changes to the API, but they still add features. When ideas come to mind, we'll add them here, but that doesn't mean they're on track for ChangeWindows 8.0.

```[tasklist]
### Feature ideas
- [ ] Revisit branding and logo
```

### Phase 4 - Release

Phase 4 is basically just shipping day preparation.

```[tasklist]
### Launch
- [ ] Setup a WordPress instance again?
- [ ] Prepare a blogpost
- [ ] Version bump API to v1, frontend to v8
- [ ] Assure all data is up-to-date with v7
- [ ] Start hosting frontend on `changewindows.org`
```
